config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  get 'messages/create'
  get 'messages/destroy'
  devise_for :users
  root to: 'posts#index'
  resources :posts do
    resources :comments, only: [:create]
  end
  namespace :api do
    # categoryを利用するためにnamespaceで個別に設定
    get '/children_category' ,to: 'categories#children_category'
  end
  resources :users, only: [:show,:update,] do
    resources :messages, only: [:index, :create, :destroy]
    member do
      post :follow_list
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/gear.rb
class Gear < ApplicationRecord
  belongs_to :post, optional: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :receive_user,class_name:'User'
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  belongs_to :category
  has_many :comments
  has_many :gears, dependent: :destroy
  accepts_nested_attributes_for :gears,allow_destroy: true

  validates :image, presence: true
  
  #postsテーブルに対して、画像アップロードを可能にするためマウント
  mount_uploader :image, ImageUploader
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  # フォロー機能のアソシエーション設定
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  # DM機能のアソシエーション設定
  has_many :messages
  has_many :sent_messages, through: :messages, source: :receive_user
  has_many :reverses_of_message, class_name: 'Message', foreign_key: 'receive_user_id'
  has_many :received_messages, through: :reverses_of_message, source: :user

  #画像アップロードのgem、carrierwaveを導入。Userテーブルのprof_imageカラムに対してuploaderを可能にする
  mount_uploader :prof_image, ImageUploader

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < ApplicationController

  def children_category
    @children_category_array = Category.find(params[:id]).children
    render '/api/children_categories.json.jbuilder', formats: 'json', handlers: 'jbuilder'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :production?
  before_action :configure_permitted_parameters, if: :devise_controller?

  def show
  end

  def edit
  end

  def update
    user = User.find(param[:id])
    user.update(configure_permitted_parameters)
    if user.save
      redirect_to user_path(current_user)
    else

    end
  end

  private

  def production?
    Rails.env.production?
  end



  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :prof_image,:text])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :prof_image,:text])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { rederect_to post_path(params[:post_id]) }
      format.json
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    send_ids = current_user.messages.where(receive_user_id: @user.id).pluck(:id)
    receive_ids = @user.messages.where(receive_user_id: current_user.id).pluck(:id)
    @messages = Message.where(id: send_ids + receive_ids).order(created_at: :desc)
    @message = Message.new
  end

  def create
    @user = User.find(params[:user_id])
    @message = current_user.messages.build(message_params)
    @message.receive_user_id = @user.id
    if @message.save
      flash[:success] = 'メッセージを送信しました。'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = 'メッセージを送信できませんでした。'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  private
  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :set_post, only: [:show]

  
  def index
    @posts = Post.all.includes(:user).order("created_at DESC")
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    @parents = Category.where(ancestry: nil)
  end

  def new
    @post = Post.new
    @post.gears.new
    @parent_category_array = []
    Category.where(ancestry: nil).each do |parent_category|
      @parent_category_array << parent_category
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path, notice: '保存されました'
    else
      redirect_to root_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_update_params)
    redirect_to root_path, notice: '修正が完了しました'
  end


  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path, notice: '投稿を削除しました'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:comment, :image, :category_id, :user_id, gears_attributes: [:equipment, :equ_comment, :_destroy, :id])
  end


  def post_update_params
    params.require(:post).permit(:comment, :image, gears_attributes: [:equipment,:equ_comment,:_destroy,:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:relationship][:follow_id])
    following = current_user.follow(user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_to user
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to user
    end
  end

  def destroy
    user = User.find(params[:relationship][:follow_id])
    following = current_user.unfollow(user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to user
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    @posts = @user.posts
  end

  def edit
    
  end

  def follow_list
    @followings = @user.followings
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.haml
%a#hamburger{:href => "javascript:void(0)"}
  %span
  %span
  %span
#overlay
#drawer-menu
  %ul
    %li.hamburger__content
      -if user_signed_in?
        = link_to user_path(current_user) do
          = image_tag current_user.prof_image, class: "hamburger__content__user__img", alt: "ほげ"
        = link_to user_path(current_user),class:"hamburger__content__user__img__name" do
          = "#{current_user.name.truncate(10, omission: '...')}さん"
      - else
        = link_to new_user_session_path do
          =icon('fas','sign-in-alt')
          ログイン
    %li
      = link_to root_path do
        = icon('fas', 'home')
        TOPへ戻る
    -if user_signed_in?
      %li
        = link_to follow_list_user_path(current_user.id), method: :post do
          = icon('fas', 'bookmark')
          フォロワーリスト
      %li
        = link_to edit_user_registration_path, method: :get do
          = icon('fas', 'user-edit')
          編集
      %li
        = link_to destroy_user_session_path, method: :delete do
          = icon('fas', 'sign-out-alt')
          ログアウト
    -else
      %li
        = link_to new_user_registration_path do
          = icon('fas', 'user-plus')
          新規会員登録
  %a#close{:href => "javascript:void(0)"}
    %span
    %span

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_post-btn.html.haml
-if user_signed_in?
  .post-btn
    = link_to new_post_path do
      = icon('far', 'image')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ShowOff
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .header
      .header__categoryArea
        -# カテゴリー
        -# .categoryMenu
        -#   .categoryMenu__parents
          -#   .categoryMenu__parents__list
          -#     = link_to "#", class: "categoryListDetail" do
          -#       .categoryListDetail--name
          -#         弦楽器
          -#       .categoryListDetail--disclosure
          -#         >
          -#   .categoryMenu__parents__list
          -#     = link_to "#", class: "categoryListDetail" do
          -#       .categoryListDetail--name
          -#         打楽器
          -#       .categoryListDetail--disclosure
          -#         >
          -# .categoryMenu__children
          -# 非同期で子カテゴリーを表示予定
            -# .categoryMenu__children__list
            -#   = link_to "#", class: "categoryListDetail" do
            -#     .categoryListDetail--name
            -#       ギター
            -#     .categoryListDetail--disclosure
            -#       >
          .categoryMenu__grandChildren
          -# 非同期で孫カテゴリーを表示予定
            -# .categoryMenu__grandChildren__list
            -#   = link_to "#", class: "categoryListDetail" do
            -#     .categoryListDetail--name
            -#       エレキギター
            -#     .categoryListDetail--disclosure
            -#       >
            -# .categoryMenu__grandChildren__list
            -#   = link_to "#", class: "categoryListDetail" do
            -#     .categoryListDetail--name
            -#       クラシックギター
            -#     .categoryListDetail--disclosure
            -#       >
      .header__title
        =link_to root_path do
          #title SHOW OFF
      .header__menu
        = render 'layouts/header'
  .contents
    = render 'layouts/notifications'
    = yield
  %footer
    = render 'shared/footer'

app/views/messages/_form.html.haml
.footer-form
  .footer-form__area
    = form_for message, :url => {:action => :create} do |f|
      = f.text_field :content, class: "new-message__text-area", placeholder: "コメントする"
      = f.submit '送信',class: "new-message__send-form"

app/views/messages/index.html.haml
.follow-msgs-content
  %h3 メッセージ一覧
  - user = User.find_by(id: @message.receive_user_id)
  -if @messages.empty?
    .follow-msgs-content__area
      まだメッセージがありません。
  -else
    - @messages.each do |message|
      .follow-msgs-content__area
        .follow-msgs-content__area__show
          .follow-msgs-content__area__show__prof
            .follow-msgs-content__area__show__prof--icon
              = image_tag message.user.prof_image, class:"user_contents__upper-info__profile--img",width: "58px",height: "58px", alt: "ほげ"
            = link_to message.user.name.truncate(10), user_path(message.user),class: "follow-msgs-content__area__show__prof--name"
          .follow-msgs-content__area__show__comment
            .follow-msgs-content__area__show__comment--detail
              = message.content
        .follow-msgs-content__area__detail
          .follow-msgs-content__area__detail--created_at
            = "投稿日時： #{message.created_at.strftime("%m/%d %H:%M")}"
          .follow-msgs-content__area__detail--delete
            - if current_user == message.user
              = link_to "削除", user_message_path(current_user, message), method: :delete, data: { confirm: "コメントを削除します。よろしいですか？" }
.follow-msgs-footer
  = render 'messages/form', message: @message
= link_to "← 戻る", root_path, class: "follow-msgs-content__back-btn"

app/views/posts/_index.html.haml
.post_content
  - posts.each do |post|
    = link_to post_path(post.id), class: "post_content__content" do
      .post_content__user
        .post_content__user__icon
          = image_tag post.user.prof_image, height: "28px", width: "28px" ,alt: "Img"
        .post_content__user__name
          = post.user.name
      .post_content__content__img-area
        = image_tag post.image ,alt: "ほげ"
      .post_content__content__text-area
        = simple_format( post.comment, {})
  = render 'layouts/post-btn'

app/views/posts/edit.html.haml
.post_create_content
  .post_create_content__title
    %h2 投稿内容の編集
    %hr

    = form_for(@post) do |f|
      .post_create_content__form
        .post_create_content__form__upper
          = f.label "コメント・自慢ポイント",class: "post_create_content__form__upper__name"
          .post_create_content__form__upper--icon
            #optional 任意
        = f.text_area :comment,autocomplete: "comment",placeholder: "熱い想いを語ろう！", class: "post_create_content__form__underTextArea"

      .post_create_content__form
        .post_create_content__form__upper
          = f.label "機材画像",class: "post_create_content__form__upper__name"
          .post_create_content__form__upper--icon
            #optional 任意
        .post_create_content__form__underImgForm--view
          = image_tag @post.image, id: "uploadImg"
        .post_create_content__form__underImgForm
          = f.file_field :image,autocomplete: "image", id: "myfile", class:"post_create_content__form__underImgForm--uploadBtn"
      %span.between-detail-margin
      %h2 機材詳細
      %hr

      = f.fields_for :gears do |i|
        #equipDetailListArea
          .equipForm{data: {equipment: "#{i.index}"}}
            .post_create_content__form{data: {equipment: "#{i.index}"}}
              .post_create_content__form__upper
                = i.label "機材名",class: "post_create_content__form__upper__name"
                .post_create_content__form__upper--icon
                  #optional 任意
              = i.text_field :equipment,placeholder: "品番、メーカーなど", class: "post_create_content__form__under"
              -if @post.persisted?
                = i.check_box :_destroy,data:{ index: i.index }, class: 'hidden-destroy'
            .post_create_content__form
              .post_create_content__form__upper{data: {equ_comment: "#{i.index}"}}
                = i.label "機材詳細",class: "post_create_content__form__upper__name"
                .post_create_content__form__upper--icon
                  #optional 任意
              = i.text_field :equ_comment,placeholder: "機材についての詳細", class: "post_create_content__form__under"
              -if @post.persisted?
                = i.check_box :_destroy,data:{ index: i.index }, class: 'hidden-destroy'

      .post_create_content__optionForm
        .post_create_content__optionForm__info
          詳細項目の追加/削除
        .post_create_content__optionForm--add
          #addEquipDetail.optionIcon
            =icon('far','plus-square')
        .post_create_content__optionForm--remove
          #removeEquipDetail.optionIcon
            =icon('far','minus-square')


      = f.hidden_field :user_id, value: current_user.id
      .post_create_content__optionForm

      .post_create_content__btnArea
        = f.submit "投稿を編集する", id: "activeBtn"

app/views/posts/index.html.haml
= render 'index', posts: @posts

app/views/posts/new.html.haml
.post_create_content
  .post_create_content__title
    %h2 機材の投稿
    %hr

    -# = form_for(@post_form, url: {controller: 'posts',action: 'create'}) do |f|
    -# post_formを使わずに投稿できるようにリファクタ
    = form_for(@post, url: {controller: 'posts',action: 'create'}) do |f|
      .post_create_content__form
        .post_create_content__form__upper
          = f.label "コメント・自慢ポイント",class: "post_create_content__form__upper__name"
          .post_create_content__form__upper--icon
            #optional 任意
        = f.text_area :comment,placeholder: "熱い想いを語ろう！", class: "post_create_content__form__underTextArea"

      .post_create_content__form
        .post_create_content__form__upper
          = f.label "機材画像",class: "post_create_content__form__upper__name"
          .post_create_content__form__upper--icon
            #requier 必須
      .post_create_content__form__underImgForm--view
        = image_tag "", id: "uploadImg"
      .post_create_content__form__underImgForm
        = f.file_field :image, id: "myfile", class:"post_create_content__form__underImgForm--uploadBtn"

      %span.between-detail-margin

      #selectCategory.post_create_content__form
        .post_create_content__form__upper{data: {category_id: "a"}}
          = f.label "カテゴリー", clas: "post_create_content__form__upper__name"
          .post_create_content__form__upper--icon
            #optional 任意
        = f.collection_select :category_id, @parent_category_array, :id, :name,{}, {class: "post_create_content__form__selecter", id: "parentSelecter"}

      %span.between-detail-margin
      %h2 機材詳細
      %hr

      = f.fields_for :gears do |i|
        #equipDetailListArea
          .equipForm{data: {equipment: "#{i.index}"}}
            .post_create_content__form
              .post_create_content__form__upper
                = i.label "機材名",class: "post_create_content__form__upper__name"
                .post_create_content__form__upper--icon
                  #optional 任意
              = i.text_field :equipment,placeholder: "品番、メーカーなど",class: "post_create_content__form__under"

            .post_create_content__form
              .post_create_content__form__upper{data: {equ_comment: "#{i.index}"}}
                = i.label "機材詳細",class: "post_create_content__form__upper__name--sub"
                .post_create_content__form__upper--icon
                  #optional 任意
              = i.text_field :equ_comment,placeholder: "機材についての詳細", class: "post_create_content__form__under"

        .post_create_content__optionForm
          .post_create_content__optionForm__info
            詳細項目の追加/削除
          .post_create_content__optionForm--add
            #addEquipDetail.optionIcon
              =icon('far','plus-square')
          .post_create_content__optionForm--remove
            #removeEquipDetail.optionIcon
              =icon('far','minus-square')

      = f.hidden_field :user_id, value: current_user.id

      .post_create_content__btnArea
        = f.submit "show off!", id: "activeBtn"

app/views/posts/show.html.haml
.post_show_contents
  =link_to user_path(@post.user.id) do
    .post_show_contents__header
      = image_tag @post.user.prof_image, class:"post_show_contents__header--img"
      .post_show_contents__header--name
        = @post.user.name
    %hr
    .post_show_contents__under__category
      - @parents.each do |parent|
        -if @post.category_id == parent.id
          .post_show_contents__under__category--parent
            = link_to '#' do
              = parent.name
            .post_show_contents__under__category--disc
              >
        //子要素までの場合
        - parent.children.each do |child|
          -if @post.category_id == child.id
            .post_show_contents__under__category--parent
              = link_to '#' do
                = parent.name
              .post_show_contents__under__category--disc
                >
            .post_show_contents__under__category--child
              = link_to '#' do
                = child.name
              .post_show_contents__under__category--disc
                >
          //孫要素までの場合
          - child.children.each do |grandchild|
            -if @post.category_id == grandchild.id
              .post_show_contents__under__category--parent
                = link_to '#' do
                  = parent.name
                .post_show_contents__under__category--disc
                  >
              .post_show_contents__under__category--child
                = link_to '#' do
                  = child.name
                .post_show_contents__under__category--disc
                  >
              .post_show_contents__under__category--grandChild
                = link_to '#' do
                  = grandchild.name

  .post_show_contents__body
    .post_show_contents__body--img
      = image_tag @post.image
    .post_show_contents__body__content
      %p.post_show_contents__body__content__comment--title
        コメント
      .post_show_contents__body__content__comment--detail
        = simple_format(@post.comment, {})
  .post_show_contents__under
    %p.post_show_contents__under__equ-title
      機材詳細
      #equ-border
    -if @post.gears.empty?
      .post_show_contents__under__no-equ-list
        機材詳細の登録はありません
    -else
      - @post.gears.each do |gear|
        %p.post_show_contents__under__equ-list--name
          = "【#{gear.equipment}】"
        %p.post_show_contents__under__equ-list--detail
          = gear.equ_comment





  .post_show_contents__editArea
    -if user_signed_in?
      -if @post.user_id == current_user.id
        =link_to edit_post_path(@post), class: "post_show_contents__editArea__editBtn" do
          投稿の編集
        =link_to post_path(@post),method: :delete, data: { confirm: '投稿を削除します。よろしいですか？' }, class: "post_show_contents__editArea__deleteBtn" do
          投稿の削除
      -else


.post_show_comments
  %h3 コメント 
  .post_show_comments__area
    - @comments.each do |comment|
      .post_show_comments__area__list
        %p.post_show_comments__area__list--name
          = link_to "#{comment.user.name}", user_path(comment.user.id)
        %p.post_show_comments__area__list--comment
          = "：#{comment.text}"

.post_show__post-comment
  .post_show__post-comment__area
    - if current_user
      = form_for([@post,@comment],id: "new_comment" ) do |f|
        = f.text_area :text,placeholder: "コメント入力", class: "msg-send-area"
        = f.submit "コメントする", class: "msg-send-button"
    - else
      .post_show__post-comment__area--noLogin
        ※※※ コメントの投稿には新規登録/ログインが必要です ※※※

= link_to "← 戻る", root_path, class: "follow-msgs-content__back-btn"

app/views/relationships/_follow_button.html.haml
- unless current_user == @user
  - if user_signed_in?
    - if current_user.following?(@user)
      = form_for(current_user.relationships.find_by(follow_id: @user.id), html: { method: :delete }) do |f|
        = f.hidden_field :follow_id, value: @user.id
        = f.submit 'フォロー中', class: 'follow-btn'
    - else
      = form_for(current_user.relationships.build) do |f|
        = f.hidden_field :follow_id, value: @user.id
        = f.submit 'フォローする', class: 'follow-btn'
  - else

app/views/shared/_footer.html.haml
.footer
  %p.footer__text
    (c) 2020 Show off

app/views/users/follow_list.html.haml
.user_follow_contents
  %h3 フォローリスト
  %hr
  - @followings.each do |follow|
    .user_follow_contents__list
      .user_follow_contents__list--icon
        = image_tag follow.prof_image, class:"user_contents__upper-info__profile--img",width: "58px",height: "58px", alt: "ほげ"
      .user_follow_contents__list--name
        = link_to "#{follow.name}さん",user_path(follow.id)
      = link_to user_messages_path(follow.id),class: "user_follow_contents__list__dm" do
        .user_follow_contents__list__dm--icon
          =icon('far','envelope')
        %p.user_follow_contents__list__dm--text
          DMを送る　
= link_to "← 戻る", root_path, class: "follow-msgs-content__back-btn"

app/views/users/show.html.haml
.user_contents
  .user_contents__upper-info
    .user_contents__upper-info__profile
      = image_tag @user.prof_image, class:"user_contents__upper-info__profile--img",width: "58px",height: "58px", alt: "ほげ"
      .user_contents__upper-info__profile--name
        = "#{@user.name}　さん"
    .user_contents__upper-info__action
      -if user_signed_in?
        -if current_user.id == @user.id
          = link_to destroy_user_session_path,class: "user_contents__upper-info__action--edit", method: :delete do
            = icon('fas', 'sign-out-alt')
            ログアウト
            %br
          = link_to edit_user_registration_path, class:"user_contents__upper-info__action--sign-out", method: :get do
            = icon('fas', 'user-edit')
            編集
        - else
          = link_to user_messages_path(@user.id), class: "user_contents__upper-info__action--edit" do
            = icon('far', 'envelope')
            メッセージを送る
          = render partial: 'relationships/follow_button', user: @user
      -else
  

  .user_contents__under-info
    .user_contents__under-info--title
      プロフィール
    %hr.border
    .user_contents__under-info--text
      = simple_format( @user.text, {})

.user_posts
  .user_posts--title
    投稿一覧
  .user_posts__list
  = render '/posts/index', posts: @posts
= link_to "← 戻る", :back, class: "follow-msgs-content__back-btn"